# Source: https://github.com/graphprotocol/graph-node/blob/02623ba2e4d20b5bd6aabdeae11947767ec84584/docker/docker-compose.yml
version: "3"
services:
  # Run an Ethereum node that forks mainnet
  eth-node:
    build: .
    # ALCHEMY_API_KEY will be read from .env or the CLI override
    environment:
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY:?ALCHEMY_API_KEY must be set}
    ports:
      - "8545:8545"
  # graph-node, ipfs and postgres are all required for running a local graph node
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "mainnet:http://host.docker.internal:8545"
      GRAPH_LOG: info
  ipfs:
    # v0.11 and higher have an issue with M1 Macs: https://github.com/ipfs/go-ipfs/issues/8645
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - "5001:5001"
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      PGDATA: "/data/postgres"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
